### ISSUE TITLE
klaus - createBidWithReferral: bidder can steal builder's reward by setting refferal as themselves

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-09-nounsbuilder-judging#281]
klaus

high

# createBidWithReferral: bidder can steal builder's reward by setting refferal as themselves

## Summary

If a bidder sets their referrer to themselves, they can receive a portion of the rewards that would otherwise belong to the builder.

## Vulnerability Detail

 

When setting the `currentBidReferral` in the `createBidWithReferral` function, it does not check if `_referral` is a bidder. So the bidder can set themselves as a referrer.

```solidity
function createBidWithReferral(uint256 _tokenId, address _referral) external payable nonReentrant {
@>  currentBidReferral = _referral;
    _createBid(_tokenId);
}
```

Normally, if there are no referrals, the referral share of the reward should go to the builder. This means that the bidder can steal some of the builder's reward tokens.

```solidity
function _computeTotalRewards(
    address _currentBidRefferal,
    uint256 _finalBidAmount,
    uint256 _founderRewardBps
) internal view returns (RewardSplits memory split) {

    ...

    // Set referral reward
@>  split.recipients[1] = _currentBidRefferal != address(0) ? _currentBidRefferal : builderRecipient;
    split.amounts[1] = (_finalBidAmount * referralRewardsBPS) / BPS_PER_100_PERCENT;

    ...
}
```

Here's the PoC code. You can add it to Auction.t.sol and run it.

```solidity
function test_FounderBuilderAndReferralReward_Selfref() external {
    // Setup
    deployAltMock(founder, 500);

    vm.prank(manager.owner());
    manager.registerUpgrade(auctionImpl, address(rewardImpl));

    vm.prank(auction.owner());
    auction.upgradeTo(address(rewardImpl));

    vm.prank(founder);
    auction.unpause();

    // Check reward values

    vm.prank(bidder1);
    auction.createBidWithReferral{ value: 1 ether }(2, bidder1);
    vm.warp(10 minutes + 1 seconds);

    auction.settleCurrentAndCreateNewAuction();

    assertEq(token.ownerOf(2), bidder1);
    assertEq(token.getVotes(bidder1), 1);

    assertEq(address(treasury).balance, 0.88 ether);
    assertEq(address(rewards).balance, 0.03 ether + 0.04 ether + 0.05 ether);

    assertEq(MockProtocolRewards(rewards).balanceOf(zoraDAO), 0.03 ether);
    assertEq(MockProtocolRewards(rewards).balanceOf(bidder1), 0.04 ether); // bidder get reward
    assertEq(MockProtocolRewards(rewards).balanceOf(founder), 0.05 ether);
}
```

## Impact

Some of the builder's rewards will be stolen.

## Code Snippet

[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/auction/Auction.sol#L145](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/auction/Auction.sol#L145)

[https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/auction/Auction.sol#L500](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/auction/Auction.sol#L500)

## Tool used

Manual Review

## Recommendation

1. Do not allow self-referrals.
2. Restrict that only the NFT owner(members of the DAO) can be set as the refferal to prevent bypassing using a user's other accounts. (If the user is already in DAO, then it could be bypassed. But this is actually means “referrer” of bid, so I think it's fine.)

**Comment by Arabadzhiew** [comment]
Escalate

Since there is no loss of funds to both the protocol and its users (due to the fact that a referral fee is going to be deducted from the winning bid at each auction settlement, no matter what, and this is the intended behavior), I believe the severity of this issue should be downgraded to ***Low/Info***.

Quoting the Sherlock docs for Criteria for Issue Validity: **Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.**

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Since there is no loss of funds to both the protocol and its users (due to the fact that a referral fee is going to be deducted from the winning bid at each auction settlement, no matter what, and this is the intended behavior), I believe the severity of this issue should be downgraded to ***Low/Info***.
> 
> Quoting the Sherlock docs for Criteria for Issue Validity: **Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.**

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@Arabadzhiew the loss of funds is the rewards that are supposed to be delegated to governance that sets a builders DAO address. It is the default address when referrals are not included so I understand why watsons included this finding, be cause this issue if figured out by users, essentially allows them to never delegate rewards to builderDAO, which defeats the whole purpose of the referral system in my eyes.

It should have been a known tradeoff explicitly mentioned in the Docs/READ.ME. But I do see your point too and was borderline about this finding, so I will leave it up to @Czar102 to decide, won't have any further inputs.

**Comment by NexxyoLabsMikelAriceta** [comment]
In my opinion the builders DAO address is already getting his rewards as we can see here: https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/auction/Auction.sol#L495-L497
They get "extra" rewards when there is no referral set, but whenever it is set they don't. This is intended and it's not a loss of rewards.

Also, the recommendation for mitigating the issue is not correct. If the only available wallet to be set as a referral was the NFT owner the referral system wouldn't make any sense. Furthermore, not allowing self-rewards is impossible, since the same user can have multiple wallets. 

In my opinion, this issue doesn't have a proper fix, since it is not an issue in the first place, it is intended behavior.

**Comment by nevillehuang** [comment]
@NexxyoLabsMikelAriceta 

This "intended" feature should have been explicitly mentioned in the DoCs/READ.ME, because it is not, I think it is fair for watsons to bring this up as a potential loss of default referral rewards to buildersDAO. I won't have any further input after this, will leave it to @Czar102.

**Comment by Arabadzhiew** [comment]
The fact that there is a referral fee functionality in the first place, signals to me that this is the intended behaviour and the protocol is ok with not receiving this ETH as a builder fee. I don't think this had to be explicitly mentioned in the contest README. After all, if that was not intentional, they would not have implemented a referral fee to begin with, right?

**Comment by nevillehuang** [comment]
> The fact that there is a referral fee functionality in the first place, signals to me that this is the intended behaviour and the protocol is ok with not receiving this ETH as a builder fee. I don't think this had to be explicitly mentioned in the contest README. After all, if that was not intentional, they would not have implemented a referral fee to begin with, right?

I think we can all agree that the intention of the referral is not to allow a self provided discount to retrieve a portion of the bid back. I only validated this because the default referral address is buildersDAO, if not if this is expected, why not just set the default refferal address back to the original bidder and not give the “extra” rewards to buildersDAO in the first place by setting such an address?

Even sponsor agrees that this should have been mentioned in the READ.ME (not that it matters). We can all try to make assumptions, signals and speculations here, but ultimately I think it is fair for watsons to bring this up as an issue.

I mean sure I get the point you guys are trying to make, and ultimately won’t disagree with @Czar102 if he decides to invalidate this issue.

**Comment by Oot2k** [comment]
I completely agree with escalation by @Arabadzhiew I think in the past these issues have always be invalid.

The referral fees are not expected income for protocol. 

I also understand @nevillehuang arguments, but I believe they are more valid in case where the protocol breaks in some way if there is self referral (Like in recent aloe contest).
This is not the case here, hence: valid low/info

**Comment by Arabadzhiew** [comment]
@nevillehuang 

Sure, the self-referral is not intended, but this issue by itself is a ***Low*** severity one at most (for the reasons I described at my initial escalation comment). Additionally, there is practically no way of preventing the funds from not being sent to the Builder DAO address, apart from removing the referral fee functionality altogether.

Don't get me wrong, I also get the point that you are trying to make. But think about this from the perspective of the watsons that also found this issue, but did not report it because they decided to obey by the Sherlock criteria for issue validity in order to protect their payout threshold - Is validating that issue fair to them?

I suggest we wait for an input from @Czar102 and continue our discussion from there.

**Comment by nevillehuang** [comment]
> @nevillehuang
> 
> Sure, the self-referral is not intended, but this issue by itself is a _**Low**_ severity one at most (for the reasons I described at my initial escalation comment). Additionally, there is practically no way of preventing the funds from not being sent to the Builder DAO address, apart from removing the referral fee functionality altogether.
> 
> Don't get me wrong, I also get the point that you are trying to make. But think about this from the perspective of the watsons that also found this issue, but did not report it because they decided to obey by the Sherlock criteria for issue validity in order to protect their payout threshold - Is validating that issue fair to them?
> 
> I suggest we wait for an input from @Czar102 and continue our discussion from there.

We can agree to disagree, but sure lets wait for head of judging to make his decision. I believe the discussion here is sufficient to reach a decision.

**Comment by slvDev** [comment]
@Arabadzhiew, but doesn't this issue breach a protocol invariant?
The protocol shouldn't allow for an `easy discount` to those who are clever enough to exploit it. While it's theoretically possible for a bidder to use a different address for self-referrals, but this cannot be proven.
Leaving the system as is undermines a core principle: **that an address should pay the full bid amount for an NFT, not less**.
 Any formal verification tool finds this as a valid path to break invariant.

**Comment by neokry** [comment]
the referral system is designed as an incentive to drive more bids. anyone that is bringing bids to the protocol should earn a reward even if that is the bidder themselves. most users will choose the path of least resistance and continue bidding from standard interfaces. the value defaults to the builder rewards address because that is assumed to be the referral ie via our interface nouns.build if no value is set. I wouldn't call the referral rewards expected revenue for the protocol as our goal is to pay this out to referrals.

**Comment by slvDev** [comment]
@neokry Thank you for your explanation. 
I understand the intention behind using the referral system as an incentive mechanism.
However, I'd like to express a concern regarding the categorization of users into those who are aware of this 'self-referral' feature and those who are not. If the protocol openly allows users to set themselves as referrals, then ideally, this option should be made clearly available and transparent to all users, possibly through the standard web interface.
This approach would ensure equitable access to the feature for everyone. If this is not the case, it might inadvertently create a scenario where only a subset of users benefit from what could be perceived as a **_secret discount_**.
Ensuring that protocol policies are clear and fair is critical to ensuring fairness among all users.

**Comment by neokry** [comment]
I agree this has potential to cause issues and we will work to mitigate these with the communities / on the interface but is a secret discount enough for this issue to be classified as medium severity? @slvDev

**Comment by slvDev** [comment]
@neokry, it's true that this "secret discount" can't directly affect the protocol's finances, but I think financial damage is possible. 
In the spirit of web3, openness and transparency are fundamental principles.
Allowing hidden discounts at the developer level, technically permissible, could compromise the trust and honesty that are vital in the web3 space. Negative perceptions, especially if spread through social media, can gradually reduce user trust in the protocol, potentially reducing the protocol's profits.
It is about protecting the reputation of the protocol, which is equally important.
Thank you for your consideration of this point of view.

**Comment by nevillehuang** [comment]
@neokry @slvDev 

The fact that you mention a “secret discount” means this was not intended, and so should have been explicitly mentioned to users/watsons alike auditing in the contest details. Since it is not, I think it is fair to keep this as medium severity from my above discussions and from the time of the contest.

Why delegate this extra rewards to buildersDAO in the first place? And to be frank as an auditor I think the whole refferals system should be kept off-chain because there is no fix to a self-refferal scenario, which I believe is not the intention of the protocol.

**Comment by neokry** [comment]
I was just using the terminology that @slvDev was using. I don't believe this feature will be secret as we are planning to allow any user to generate a referral link and claim rewards. I agree this tradeoff should have been mentioned which is why I confirmed this issue in the first place. the extra rewards are delegated to builder DAO because we host the primary interface for the protocol and if a referral is not set it is assumed the user has bid from our interface with no referral like I mentioned previously. 

the referral rewards will be set to 1.5% of the final bid and most DAOs have auctions that settle for < 1 ETH. even at 1 ETH this referral reward will only be 0.015 ether ie 30 USD at current market price which essentially equates to a gas refund for mainnet bidders atm. in a realistic scenario bidders self referring will not have a significant advantage in auctions as our auctions do not go for significant amount of value and the feature will primarily be used for interfaces to become sustainable if they can regularly be the referral for a % of daily bids.

**Comment by nevillehuang** [comment]
@neokry 

I get your point on the current pricing of NFTs and so on. But you are also implying that in the future NFTs wont have a higher bid price and refferal reward cannot be a higher percentage, which is not unlikely. So I suggest to keep this issue as medium severity.

**Comment by Czar102** [comment]
I see no fundamental reason why wouldn't it possible for a user to refer themselves or why should the code discriminate an arbitrary identity in a world where anyone can have an infinite number of those.

Per sponsor comment:
> the value defaults to the builder rewards address because that is assumed to be the referral ie via our interface nouns.build if no value is set

I consider this an informational issue as it's clearly a direct consequence of the design, and there is no attack possible. The contract doesn't leak value and this referral payment to the builder is optional according to the design (i.e. others may claim a referral).

Planning to accept the escalation and invalidate the issue.

**Comment by nevillehuang** [comment]
Ok watsons if head of judging @Czar102 says so i cannot defend you guys anymore 🤣.  

Also is the sponsor @neokry  implying something from the front-end not related to the contracts? If so there could be judging inconsistencies here.

If true, this is essentially saying, if I interact with the contracts directly, not the front-end, I can get a self-discount from a refferal and not pay buildersDAO. Sure this could be design opinion, but where was it highlighted to watsons during the contest other than vague implications and assumptions?

Again disappointed how an assumption not explicitly stated can be put on watsons for submitting this issue and lead judge judging.

**Comment by vararg** [comment]
@Czar102 I believe this is a lack of documentation for this specific DAO or audit. Because "referral" concept is not something new and unique - and it always states to something like "when someone recommends your business to another person, they receive some kind of reward in return" . 
The way how Nouns Builder made this referral system is unique, because self referral make no sense for the stale concept above, and even more corrupt this principle. So users, auditors and everyone who work with that contract should be informed about that.

And that's totally fine to say that issue is low, but saying is works as intended is a bit speculative(of course if it's not stated somewhere in the documentation).

When someone call something a "duck", it looks like a "duck", of course you will expect to see a "duck" and will disagree if it's a goose in result.

**Comment by neokry** [comment]
zora uses this same referral model @vararg snd our implementation is based on how it works and uses the same protocol rewards contract.

**Comment by vararg** [comment]
@neokry Yes, and Zora has a proper documentation about that because it's a specific use case for their contract https://support.zora.co/en/articles/8192123-understanding-protocol-rewards-on-zora.

**Comment by chinmay-farkya** [comment]
> If true, this is essentially saying, if I interact with the contracts directly, not the front-end, I can get a self-discount from a refferal and not pay buildersDAO. Sure this could be design opinion, but where was it highlighted to watsons during the contest other than vague implications and assumptions?

That is the real problem imo. Some who can read code will know about this secret discount and others will not, which is unfair to normal users unless it had been explicitly stated everywhere. So this should remain as medium severity.

**Comment by Arabadzhiew** [comment]
I think this discussion is starting to go a bit too far off from the actual vulnerability at question. Since when exactly are we taking the front-end of protocols into consideration during smart contract security reviews? Let's please keep things to only what's in scope.

**Comment by nevillehuang** [comment]
@Arabadzhiew yes there should be no discussion revolving validity of a vulnerability from a front-end point of view. But the sponsor seem to be implying so based on the above [comment](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/281#issuecomment-1858535321) when he is mentioning "interface", that is why I am trying to clarify.

**Comment by Czar102** [comment]
It is clear that this fee will be gathered by the **interface** or an address that the interface chooses, and it is clear to me from the design perspective that it was the intention.

If you found the project by yourself and built infrastructure on it so that you can mint for yourself, I think it makes sense for you to receive that referral fee.

I stand by the first sentence of [my initial response](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/281#issuecomment-1858542154).

**Comment by nevillehuang** [comment]
> It is clear that this fee will be gathered by the **interface** or an address that the interface chooses, and it is clear to me from the design perspective that it was the intention.
> 
> If you found the project by yourself and built infrastructure on it so that you can mint for yourself, I think it makes sense for you to receive that referral fee.
> 
> I stand by the first sentence of [my initial response](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/281#issuecomment-1858542154).

This is actually a really good take, but I hope this is actually made clear to members participating in the DAO though, because the contract logic caused this confusion that made me misjudged this issue.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Arabadzhiew](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/281/#issuecomment-1854665051): accepted
