### ISSUE TITLE
ZanyBonzy - Revoked operator can still call the transferFrom function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#6]
ZanyBonzy

medium

# Revoked operator can still call the transferFrom function

## Summary
There is no way to revoke the approval which given via the `approve` function. They are able to call the `transferFrom` even after the tokenHolder revokes all permissions using the `setApprovalForAll` function. 
## Vulnerability Detail
Alice holds the token.

She approves Bob via `setApprovalForAll(_Bob, _true)`, which gives Bob access to the token, he's now operatorApproved.
```solidity
    function setApprovalForAll(address _operator, bool _approved) external {
        operatorApprovals[msg.sender][_operator] = _approved;

        emit ApprovalForAll(msg.sender, _operator, _approved);
    }
```
Bob approves himself `approve(_Bob, _tokenId)` and is now both operatorApproved and tokenApproved, for the tokens.
```solidity
    function approve(address _to, uint256 _tokenId) external {
        address owner = owners[_tokenId];

        if (msg.sender != owner && !operatorApprovals[owner][msg.sender]) revert INVALID_APPROVAL();

        tokenApprovals[_tokenId] = _to;

        emit Approval(owner, _to, _tokenId);
    }
```
Alice revokes Bob's approval by calling `setApprovalForAll(_Bob, _false)`, now Bob is no longer operatorApproved, but still tokenApproved.

Now Bob can still call the .transferFrom(_Alice, _to, _tokenId) which is subjected to call only by approved address.
```solidity
       if (msg.sender != _from && !operatorApprovals[_from][msg.sender] && msg.sender != tokenApprovals[_tokenId]) revert INVALID_APPROVAL();
```
The transfer will be successful.

## Impact
Bob can call the `transferFrom` and potentially cost Alice her tokens.
## Code Snippet
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/lib/token/ERC721.sol#L115
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/lib/token/ERC721.sol#L102
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/db232c649b425c36f5a93607c95cfdf0e5962b2f/nouns-protocol/src/lib/token/ERC721.sol#L125C1-L151C6
## Tool used

Manual Review

## Recommendation
Revoke all operator's tokenApprovals after his approval gets revoked or prevent self approvals by operators.

**Comment by ZanyBonzy** [comment]
Escalate

Hi, I believe i didn't do a good job of communicating the issue, which is the reason for this. I went about it from the point of view that a user has just one token, which is where the confusion stems from. Apologies, i'm a little slow in my English.

My whole point hinges on the fact that, operators can approve tokens to themselves, and that their token approvals aren't cleared  after their status is revoked.

What i was trying to explain is this, Alice approves Bob to be in charge of her all her tokens. After a while, she decides, she's want to be in charge and decides to revoke Bob's approval. Bob sees this, frontruns the approval, and approves himself to specific tokens (using the approve function). After his operator role is revoked, he can still transfer those specific tokens that he managed to approve to himself due to his token approval. 

@nevillehuang to tweak your scenario

1. Owner has 10 tokens
2. He sets approval for all to spender
3. Owner decides to revoke approval for all to spender
4. Spender frontruns owner and approves himself token id 0 and token id 1
5. Owner revokes approval for all to spender
6. Spender still has access to token id 0 and token id 1, basically defeating the purpose of his revoked approval.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Hi, I believe i didn't do a good job of communicating the issue, which is the reason for this. I went about it from the point of view that a user has just one token, which is where the confusion stems from. Apologies, i'm a little slow in my English.
> 
> My whole point hinges on the fact that, operators can approve tokens to themselves, and that their token approvals aren't cleared  after their status is revoked.
> 
> What i was trying to explain is this, Alice approves Bob to be in charge of her all her tokens. After a while, she decides, she's want to be in charge and decides to revoke Bob's approval. Bob sees this, frontruns the approval, and approves himself to specific tokens (using the approve function). After his operator role is revoked, he can still transfer those specific tokens that he managed to approve to himself due to his token approval. 
> 
> @nevillehuang to tweak your scenario
> 
> 1. Owner has 10 tokens
> 2. He sets approval for all to spender
> 3. Owner decides to revoke approval for all to spender
> 4. Spender frontruns owner and approves himself token id 0 and token id 1
> 5. Owner revokes approval for all to spender
> 6. Spender still has access to token id 0 and token id 1, basically defeating the purpose of his revoked approval.
> 
> 
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by nevillehuang** [comment]
> Escalate
> 
> Hi, I believe i didn't do a good job of communicating the issue, which is the reason for this. I went about it from the point of view that a user has just one token, which is where the confusion stems from. Apologies, i'm a little slow in my English.
> 
> My whole point hinges on the fact that, operators can approve tokens to themselves, and that their token approvals aren't cleared after their status is revoked.
> 
> What i was trying to explain is this, Alice approves Bob to be in charge of her all her tokens. After a while, she decides, she's want to be in charge and decides to revoke Bob's approval. Bob sees this, frontruns the approval, and approves himself to specific tokens (using the approve function). After his operator role is revoked, he can still transfer those specific tokens that he managed to approve to himself due to his token approval. Also notice that there's no way to revoke this approval unless by transfering those tokens.
> 
> @nevillehuang to tweak your scenario
> 
> 1. Owner has 10 tokens
> 2. He sets approval for all to spender
> 3. Owner decides to revoke approval for all to spender
> 4. Spender frontruns owner and approves himself token id 0 and token id 1
> 5. Owner revokes approval for all to spender
> 6. Spender still has access to token id 0 and token id 1, basically defeating the purpose of his revoked approval.

@ZanyBonzy 
I think front-running approvals is not accepted as a valid medium severity issue anymore. This behavior is also present in OZ's implementation. I agree with @IAm0x52 that it is users responsibility to call `setApprovalForAll()` appropriately, given the spender can immediately spend the tokens, I don't see the need of front-running.

**Comment by ZanyBonzy** [comment]
Fair enough point, and even if the approvals isn't front ran. The fact that token approvals can exist for the operator before the operator's approval is revoked is still a cause for concern, in my opinion.

**Comment by ZanyBonzy** [comment]
@nevillehuang Thanks for your time, really appreciated,

Fair enough point. But, even if the approvals isn't front ran. The fact that individual token approvals can exist (and can not be revoked) for an operator even after the operator's approval is revoked is still a cause for concern, in my opinion. That is, if he had approved himselfs individually to the tokens, before his operator status got revoked, he still has access to the tokens which defeats the purpose of the revokal. I used front running as an extreme example, it could have happened any time before.
 
My basic view is that an operator should not be able to also approve himself to the individual tokens, or/and that if he should/can, his token approvals should be cleared also when his approve for all status is revoked. Its one of the reasons for my recommendation and also for setting it as a medium. Its a high risk issue because possible loss of tokens with a low probability of occurrence because it takes special cases. 
As per being OZ's implementation, i believe we can agree that OZ contracts are not perfect, still have vulnerabilities.

Also please take a look at slightly similar issue [here](https://github.com/code-423n4/2023-09-delegate-findings/issues/383)
