### ISSUE TITLE
ggg_ttt_hhh - Founders may receive a higher number of tokens than initially anticipated.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-nounsbuilder-judging#70]
ggg_ttt_hhh

medium

# Founders may receive a higher number of tokens than initially anticipated.

## Summary
There are predefined percentage values that signify the proportion of tokens allocated to `founders`. 
For instance, if the cumulative percentage value for all `founders` is `50`, it implies that approximately half of the tokens should be allocated to the `founders`. 
This mechanism is designed to maintain a balance in the distribution of tokens between `founders` and regular `users` within the protocol.
However, this equilibrium can be disrupted when there are no bids for certain tokens.
## Vulnerability Detail
When creating an `auction`, a new token was minted and subsequently assigned to the auction contract.
```solidity
function _createAuction() private returns (bool) {
    try token.mint() returns (uint256 tokenId) {}
}
```
```solidity
function mint() external nonReentrant onlyAuctionOrMinter returns (uint256 tokenId) {
    tokenId = _mintWithVesting(msg.sender);
}
```
To generate this new token, a certain number of tokens were minted and allocated to the `founders` based on the specified `proportion`.
```solidity
function _mintWithVesting(address recipient) internal returns (uint256 tokenId) {
    unchecked {
        do {
            tokenId = reservedUntilTokenId + settings.mintCount++;
        } while (_isForFounder(tokenId));
    }
    _mint(recipient, tokenId);
}
```
If there is no bid for this token, it is necessary to burn the token.
```solidity
function _settleAuction() private {
    if (_auction.highestBidder != address(0)) {
    } else {
         token.burn(_auction.tokenId);
    }
}
```
However, in the `burn` function, we do not decrease `settings.mintCount`. 
Therefore, irrespective of whether this token is assigned to a `user` or burned, the same `process` will continue for subsequent tokens.
```solidity
function _burn(uint256 _tokenId) internal override {
    super._burn(_tokenId);
    unchecked {
        --settings.totalSupply;
    }
}
```

The POC test is as below:
```solidity
function test_NoBid() public {
      address f1Wallet = founder;
      uint256 f1Percentage = 50;
      address[] memory founders = new address[](1);
      uint256[] memory percents = new uint256[](1);
      uint256[] memory vestingEnds = new uint256[](1);
      founders[0] = f1Wallet;
      percents[0] = f1Percentage;
      vestingEnds[0] = 4 weeks;

      deployWithCustomFounders(founders, percents, vestingEnds);
      Founder memory f1 = token.getFounder(0);
      assertEq(f1.ownershipPct, f1Percentage);

      vm.prank(founder);
      auction.unpause();

      uint256 skipTime = 20 minutes;
      for (uint256 i; i < 99; i++) {
          vm.warp(skipTime * (i + 1));
          auction.settleCurrentAndCreateNewAuction();
      }

      assertEq(token.balanceOf(f1Wallet), 100);
      // The final auction has not been settled yet.
      assertEq(token.totalSupply(), 101);
  }
```
As evident, the protocol balance is `50`, but all tokens were allocated to the `founders`.
## Impact
After deploying the `DAO` and initiating its auction, there is no guarantee that the `auction` process will unfold as expected. 
If there are no `bids` for a certain period due to various reasons, all created tokens will be assigned to the `founders`, disrupting the intended balance. 
To manage the balance, additional measures such as updating the `founder`'s percentage or implementing other adjustments may be necessary.
## Code Snippet
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L294
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L201-L203
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L230-L243
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L285
https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L302-L310
## Tool used

Manual Review

## Recommendation
Modify `_burn` function as below:
```solidity
function _burn(uint256 _tokenId) internal override {
    // Call the parent burn function
    super._burn(_tokenId);

    // Reduce the total supply
    unchecked {
        --settings.totalSupply;
        
        + if (settings.mintCount > 0 && reservedUntilTokenId + settings.mintCount - 1 == _tokenId) settings.mintCount--;
    }
}
```
This ensures that no new tokens are assigned to the `founders` until a successful `auction` takes place.
As a result, the overall balance of the protocol will be maintained.

**Comment by rvierdiiev** [comment]
Escalate.

This issue describes exactly the same thing, that was disscussed in the previous c4 audit. If you look into the issue, then you will see, that the problem was that when tokens are burnt, because they were not sold, then percentage of owner's tokens in circulation is bigger than it was set in the founders settings.

The protocol has changed the code a little bit, so now in case of burning, they decrease settings.totalSupply(which fixes other issue found by c4 audit, [before they didn't do that](https://github.com/code-423n4/2022-09-nouns-builder/blob/main/src/token/Token.sol#L207-L213). And they have added additional param settings.mintCount, which [is increased with each new minted token](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L235) for the auction and exactly this param now behaves similar to the settings.totalSupply param from previous audit([before settings.totalSupply++ was used](https://github.com/code-423n4/2022-09-nouns-builder/blob/main/src/token/Token.sol#L154) to check if token belongs to owner).

As result, we can see that this is exactly same issue that was found in c4 audit and was confirmed(not acknowledged) by sponsor team. Also i want to say that confirmed label means that protocol realizes that finding is an issue, which usually means that if same issue is still present in the code, then it is valid. Also i should say, that there was no any additional info which states that this issue is out of scope as they decided to move further with it. That's said i believe that issue is valid medium.

Also i would like to add few more words about why such behaviour is not good for the DAO.
Auction.settleCurrentAndCreateNewAuction can be called [by anyone](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L238-L241), which will settle previous auction(burn token if no one bought) and then start another one(mints another token). Because of that fact in times when users are not interested in purchasing new tokens, settleCurrentAndCreateNewAuction function call will make additional tokens to be minted to the owners(so totalSupply will be increasing). As no value is added to the dao(tokens are minted for free) that means that such action will actually move tokens price down as their amount on the market is increased, but DAO didn't receive additional costs. So it's in interests of DAO and owners to not mint additional tokens to the owners, when no one purchases tokens and not decrease nft cost.

Now i will comment on some sponsor statements:
> Founders allocation is not a % of total supply it is a % of all minted tokens.

I should say that there is no any info about that and according to the previous audit, allocation should be % of total supply and this makes sense to me.

> Founders should receive their allocation if auctions are successful or not. If there is no demand at the moment founders can choose to leave auctions unsettled until a bidder is interested

As i already said above settleCurrentAndCreateNewAuction can be called by anyone, so founders actually can't leave auctions unsettled as anyone can call function.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> This issue describes exactly the same thing, that was disscussed in the previous c4 audit. If you look into the issue, then you will see, that the problem was that when tokens are burnt, because they were not sold, then percentage of owner's tokens in circulation is bigger than it was set in the founders settings.
> 
> The protocol has changed the code a little bit, so now in case of burning, they decrease settings.totalSupply(which fixes other issue found by c4 audit, [before they didn't do that](https://github.com/code-423n4/2022-09-nouns-builder/blob/main/src/token/Token.sol#L207-L213). And they have added additional param settings.mintCount, which [is increased with each new minted token](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L235) for the auction and exactly this param now behaves similar to the settings.totalSupply param from previous audit([before settings.totalSupply++ was used](https://github.com/code-423n4/2022-09-nouns-builder/blob/main/src/token/Token.sol#L154) to check if token belongs to owner).
> 
> As result, we can see that this is exactly same issue that was found in c4 audit and was confirmed(not acknowledged) by sponsor team. Also i want to say that confirmed label means that protocol realizes that finding is an issue, which usually means that if same issue is still present in the code, then it is valid. Also i should say, that there was no any additional info which states that this issue is out of scope as they decided to move further with it. That's said i believe that issue is valid medium.
> 
> Also i would like to add few more words about why such behaviour is not good for the DAO.
> Auction.settleCurrentAndCreateNewAuction can be called [by anyone](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/auction/Auction.sol#L238-L241), which will settle previous auction(burn token if no one bought) and then start another one(mints another token). Because of that fact in times when users are not interested in purchasing new tokens, settleCurrentAndCreateNewAuction function call will make additional tokens to be minted to the owners(so totalSupply will be increasing). As no value is added to the dao(tokens are minted for free) that means that such action will actually move tokens price down as their amount on the market is increased, but DAO didn't receive additional costs. So it's in interests of DAO and owners to not mint additional tokens to the owners, when no one purchases tokens and not decrease nft cost.
> 
> Now i will comment on some sponsor statements:
> > Founders allocation is not a % of total supply it is a % of all minted tokens.
> 
> I should say that there is no any info about that and according to the previous audit, allocation should be % of total supply and this makes sense to me.
> 
> > Founders should receive their allocation if auctions are successful or not. If there is no demand at the moment founders can choose to leave auctions unsettled until a bidder is interested
> 
> As i already said above settleCurrentAndCreateNewAuction can be called by anyone, so founders actually can't leave auctions unsettled as anyone can call function.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@rvierdiyev 

I am leaning towards agreeing with you as can be seen that I initially validated both of the findings, but ultimately it is not my decision to make and will leave it in the hands of @Czar102.

**Comment by neokry** [comment]
I get your point @rvierdiyev but why would anyone be settling auctions for a DAO they don’t care about. If nobody is interested in joining the DAO and the founders are not settling auctions they usually just remain unsettled until a bidder is interested especially when settling involves minting founders tokens as those transactions are more expensive than usual.

**Comment by rvierdiiev** [comment]
When we do security review, we usually look into all possible edge cases.
I can't provide an exact reason why someone would do that, but i definitely see that this is possible to do.

From the founder's perspective, he can do that to get more nfts(because his vesting is going to be finished soon and he wants to get bigger amount and believes that these tokens will increase in price later or to have bigger amount of votes in the DAO governance) and when founder mints additional tokens, then his total nfts value remains approximately same(as nft price has decreased, but new nft is minted to owner), but nft value decreases for all other members.

Also i have one more thought why allocation should be % of total supply. It's because we can think about allocation like the percentage of total votes of the founder that should be received from vesting. In case if token is burnt after it wasn't purchased on auction, then this votes percentage changes and founder gets bigger amount(and has more control over DAO). In times when no one is interested in purchasing, the founder can call settleCurrentAndCreateNewAuction to get additional voting power and increase his control over DAO.

**Comment by nevillehuang** [comment]
Agree with @rvierdiyev, I think this is a valid medium severity issue as I don't believe founders are trusted entities anymore after auction commences and ownership has transferred to the DAO, with #191 being an additional duplicate.

**Comment by neokry** [comment]
I agree this is a potential issue but founders are configured by admin and if admin is setting malicious founders couldn't that be considered an admin misconfiguration? @nevillehuang

**Comment by nevillehuang** [comment]
@rvierdiyev Correct me if I’m wrong but this occurs after auction commences and founders has been set before correct? If so this is not admin configuration given it can occur in regular flow of auction where founders are no longer admins

**Comment by neokry** [comment]
the issue happens during auction flow but the deployer / DAO admin decides who are founders and how much allocation they receive. if founders are trying to rug the project by inflating their supply then the admin set founders that are not aligned with the DAO. to me this could be seen as an admin issue same as if admin set founders with > 50% allocation and they decide to rug the DAO.

**Comment by nevillehuang** [comment]
I think the key difference here is there is unintentional allocation of tokens to founders (it doesn’t even have to be those numbers you are stating), giving them extra tokens to vote then intended. Founders are part of the DAO after ownership transfer, so they should be only receiving their intended token allocation, not anything extra to maintain a fair governance. To me this is not equivalent to a rugpull scenario

**Comment by neokry** [comment]
like I mentioned the founders are never expected to receive x% of totalSupply. imo it was a design decision from the original developers to have founders receive x% of all tokens minted. even if they confirmed an issue from last audit related to this they decided to ship with the behavior as is and we should be looking at this from a clean slate.

**Comment by nevillehuang** [comment]
If the previous developers confirmed the issue and 

1. Did not specify why they shipped this without implementing a fix
2. You didn’t specify to watsons this is intended design decision in the contest details

Then I don’t see why this shouldn’t be a valid issue watsons bring up again. I will let the watson continue the discussion and ultimately let @Czar102 decide whether or not to validate issue, but I am in support of validating as medium severity and see no reason to see the contract as a clean slate unless the above stated points are untrue.

**Comment by rvierdiiev** [comment]
> I agree this is a potential issue but founders are configured by admin and if admin is setting malicious founders couldn't that be considered an admin misconfiguration?

it should not be considered an admin misconfiguration
admin can't know if someone of founders will act maliciously, this is logic flow from my point of view

> as I don't believe founders are trusted entities anymore

they are not, they are just humans :)

> to me this could be seen as an admin issue same as if admin set founders with > 50% allocation and they decide to rug the DAO.

but also admin can set founders with <50%(to not allow them rug the DAO), but because of this issue they still can get >50%

**Comment by Czar102** [comment]
I don't think founders are trusted entities. Additionally, the protocol team hasn't outlined them in the README in the protocol roles section.

I think the intentions were clear, as expressed [in this comment](https://github.com/sherlock-audit/2023-09-nounsbuilder/blob/main/nouns-protocol/src/token/Token.sol#L118) in the code. I think this approach also presents a valid design. In the end, if the DAO control is at all valued (even beyond monetary value), some parties would certainly bid 1 wei for the token. If not, then founders could get *additionally* these tokens for 1 wei (which is always a good business because that's pretty much nothing, they spend more on minting their own tokens anyway), so all governance safety mechanisms break down, and it's not even specific to the founders (others can mint the "free" tokens as well), and they can eventually hijack the governance. I think this is a part of the design.

Hence, I am planning to reject the escalation and leave the issue as is.

**Comment by nevillehuang** [comment]
@Czar102 Again I wont argue with you stance. I can semi agree with your point given this is an edge case relying on a auction with no bidders. However the points you bring up while reasonable, makes alot of assumptions on how founders would act. What if they don’t act according to what you highlighted? I think that is what watsons are trying to convey here as an edge case. Also understand C4 and sherlock have vastly different rules of what constitutes a medium severity finding, given this similar issue was accepted as a medium in the previous C4 contest.

Regardless of the severity, I am glad watsons brought this up.

**Comment by Czar102** [comment]
> However the points you bring up while reasonable, makes alot of assumptions on how founders would act.

My main point is that the whole system breaks down if there are no bids (because anyone can buy a token for 1 wei). I don't think this makes any assumptions about founders, previous message was just an example of what may happen anyway.

**Comment by nevillehuang** [comment]
> > However the points you bring up while reasonable, makes alot of assumptions on how founders would act.
> 
> My main point is that the whole system breaks down if there are no bids (because anyone can buy a token for 1 wei). I don't think this makes any assumptions about founders, previous message was just an example of what may happen anyway.

Fair point, thanks for the clarification, I agree with your reasoning EXCEPT when the minimum bid price is reasonably high, then I believe this scenario can occur.

**Comment by Czar102** [comment]
That's true, I believe this is a design choice anyway, as communicated the comments in code. Founders should receive tokens independently of whether there is demand for new tokens, so it is natural that their share could increase towards 100% and make them control the DAO.

**Comment by rvierdiiev** [comment]
hey @Czar102 
The comment that you provided doesn't say anything about design it just says about tokens mapping.
Even if this is design decision this report and other linked have shown why it's not a good idea and why it should not be like that. I am trying to say that not each design decision is good.

**Comment by Czar102** [comment]
> The comment that you provided doesn't say anything about design it just says about tokens mapping.

Let me bring the comment up:
> We do this by reserving an mapping of [0-100] token indices, such that if a new token mint ID % 100 is reserved, it's sent to the appropriate founder.

The code works as the comment states and I believe the consequences aren't undesired.
> I am trying to say that not each design decision is good.

Design improvements are not issues and hence are out of scope.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-09-nounsbuilder-judging/issues/70/#issuecomment-1855405604): rejected
